### ISSUE TITLE
Combining lines shorter the fill column leads to invalid code

### ISSUE THREAD

**Issue by delexi** [ektrah/vs-reflow#1]
Given this comment in either a .cs or .js file where `[` marks the beginning of the selection and `]` the end:
```
            [// This text describes the stryker.pss.modal module. It outlines
            // what it does, how it does those things and why.]
```

Pressing Ctrl-K Ctrl-Q with the reflow column set to 115 produces this:
```
            // This text describes the stryker.pss.modal module. It outlines // what it does, how it does those
            things and why.
```

Whereas I would have expected it to produce this instead:
```
            // This text describes the stryker.pss.modal module. It outlines what it does, how it does those 
            // things and why.
```

**Comment by ektrah** [comment]
The extension is really simple and assumes that everything is plain text. It's unaware of characters indicating comments and just treats them like any other word.

I've considered adding support for reflowing comments, but since there are so many different ways to write comments in different programming languages and there are already other extensions that reflow comments, I decided to keep it simple.

**Comment by delexi** [comment]
Ok, that is understandable. Do you know of an extension that does comment reflowing for .cs (and maybe .js) files in VS2017?

**Comment by ektrah** [comment]
[Comment Reflower](https://marketplace.visualstudio.com/items?itemName=codebeast.CommentReflower) seems to be fairly popular. I haven't tried it though.
