### ISSUE TITLE
Support for formatting xmldoc comments?

### ISSUE THREAD

**Issue by fpintos** [ektrah/vs-reflow#2]
It would be great if this extension were to detect and take into consideration the type of text being formatted, in particular, xmldocs.

Right now, invoking reflow when you have xmldoc selected leave us with non-working code.
The workaround is to write each xmldoc paragraph in a separate text file, reflow and then bring into code.

If the extension kept the xmldoc tags intact and formatted just the text inside, it would be good.

**Comment by ektrah** [comment]
Support for formatting comments and XML docs would be nice, but requires some smartness that the extension does not have. The extension just assumes plain text and treats any sequence of non-whitespace characters as a word. Anything more would probably require something based on Roslyn. Since there is already [at least one extension](https://marketplace.visualstudio.com/items?itemName=codebeast.CommentReflower) on the VS Marketplace that seems to support formatting XML docs, I'd like to keep it simple for now. (I haven't tried that extension, though.)

**Comment by fpintos** [comment]
Cool, thanks for the pointer.
