### ISSUE TITLE
Did this get used/included into Visual Studio?

### ISSUE THREAD

**Issue by StingyJack** [ektrah/vs-reflow#3]
It shows up in [stack traces](https://developercommunity.visualstudio.com/content/problem/350167/nullreferenceexception-at-microsoftvisualstudiotex.html)  when the compare window has problems,  I dont think I installed this extension, did it get packaged into VS?

**Comment by ektrah** [comment]
I'm not aware that the extension has been included in Visual Studio. If you didn't install the extension, it shouldn't show up in any stack traces. However, if you have it installed, then it can show up in stack traces even if it didn't cause the exception due to the way Visual Studio chains command handlers. (That doesn't of course rule out that the extension is the cause of exceptions. So feel free to point me to stack traces in which it's showing up and I'll take a look. In the linked case, I don't see anything that could point at my code as the exception cause.)

**Comment by StingyJack** [comment]
This did look like a casualty of something else crashing. I've reported editor/merge/compare window crashes to MSFT a few times already and they zone in on anything in the stack that doesn't start with "Microsoft" or "System", and I was curious about where this came from. I'll leave them to figure it out. Thanks for the prompt response.
